default: &default
  username: danghanh  
  password: ledanghanh
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: apartment_development

test:
  <<: *default
  database: apartment_test
 
production:
  <<: *default
  database: apartment_production
  
