development:
  adapter: postgresql
  encoding: unicode
  database: apartment_development
  pool: 5
  timeout: 5000
  username: danghanh  
  password: ledanghanh

test:
  adapter: postgresql
  encoding: unicode
  database: apartment_test
  pool: 5
  timeout: 5000
  username: danghanh
  password: ledanghanh

production:
  adapter: postgresql
  encoding: unicode
  database: apartment_production
  pool: 5
  timeout: 5000
  username: danghanh
  password: ledanghanh
